### ISSUE TITLE
TypeError: Super expression must either be null or a function, not undefined

### ISSUE THREAD

**Issue by canercak** [rcaferati/react-awesome-button#45]
Hi I'm getting below error when I run a page with awesome button on my ubuntu server. The same code works in my local mac. I tried removing awesome button code and everything worked fine.
```

TypeError: Super expression must either be null or a function, not undefined
at https://bethabit.com/containers-OfferPage.55094d78b16709c57ee7.js:1:7370
at https://bethabit.com/containers-OfferPage.55094d78b16709c57ee7.js:1:7453
i
at webpack:///home/ubuntu/bethabit/node_modules/react-awesome-button/dist/index.js:1:12253
call
at webpack:///home/ubuntu/bethabit/node_modules/react-awesome-button/dist/index.js:1:465
n
at webpack:///home/ubuntu/bethabit/node_modules/react-awesome-button/dist/index.js:1:1419
call
at webpack:///home/ubuntu/bethabit/node_modules/react-awesome-button/dist/index.js:1:465
n
at webpack:///home/ubuntu/bethabit/node_modules/react-awesome-button/dist/index.js:1:6376
call
at webpack:///home/ubuntu/bethabit/node_modules/react-awesome-button/dist/index.js:1:465
n
at webpack:///home/ubuntu/bethabit/node_modules/react-awesome-button/dist/index.js:1:1268
Object.1038
at webpack:///home/ubuntu/bethabit/node_modules/react-awesome-button/dist/index.js:1:1285


```
I use it as below

```

import { AwesomeButton } from 'react-awesome-button';
import AwesomeButtonStyles from 'react-awesome-button/src/styles/styles.scss';


   const aButton = () => {
      return (
        <div className="text-center">
          <AwesomeButton
            type="primary"
            className="aws-btn-big"
            onPress={() => {
              this.toggle();
            }}
          >
            Download Your 21 Day Challenge Guide
          </AwesomeButton>
          <div className="padTop5">
            <p className="stock-message">
              Hurry! This Offer Ends <span className="today">Soon!</span>
            </p>
          </div>
        </div>
      );
    };
 <p className="offer_subheadline">{offercontent.intro.subtitle}</p>
  {aButton()}
```

**Comment by rcaferati** [comment]
Hey @canercak, thanks for raising it. I've updated it can you test it out if you're still getting this on `v6.4.0`?
